image: docker:latest

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance:
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: "nuxtemp"
  GROUP_NAME: "Anibal Aguila <aa@stk.ac>"
  CONTAINER_TEST_IMAGE: "registry.gitlab.com/$GROUP_NAME/$PROJECT_NAME:$CI_BUILD_REF_NAME"
  CONTAINER_RELEASE_IMAGE: "registry.gitlab.com/$GROUP_NAME/$PROJECT_NAME:latest"

services:
  - docker:dind

before_script:
  # Installing docker-compose:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip git build-base
  - pip install docker-compose
  # Creating test configuration file:
  - cp config/.env.template config/.env
  # Login into Docker registry:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  # Debug information:
  - docker info
  - docker-compose --version
  - git --version

# Build Docker container and push it to the Gitlab's registry:
build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE --build-arg APP_ENV=production -f docker/django/Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE

# Testing application:
test:
  stage: test
  script:
    - docker-compose run vue yarn ci
  coverage: '/All files\s*\|\s*([\d\.]+)/'

# Releasing image, when tests pass:
release-image:
  stage: deploy
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  environment:
    name: production
